# These are supported funding model platforms

github: anonymous14725 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon:anonymous14725 # Replace with a single Patreon username
open_collective:anonymous14725 # Replace with a single Open Collective username
ko_fi:anonymous14725 # Replace with a single Ko-fi username
tidelift:nuget/hackX # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge:anonymous14725 # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay:anonymous14725 # Replace with a single Liberapay username
issuehunt:anonymous14725 # Replace with a single IssueHunt username
otechie:anonymous14725 # Replace with a single Otechie username
custom:www.plplanguage.ir # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
